version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - /home/cedrick/Docker/Symfony/src:/home/wwwroot/sf4/
        depends_on:
          - php

    db:
        image: mysql
        container_name: sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - /home/cedrick/Docker/Symfony/src:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - db
  
    phpmyadmin:
        image: corbinu/docker-phpmyadmin
        links:
          - db:mysql
        ports:
          - 8181:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80